export const CONTACT_INFO = {
  email: "info@jcvgebrook.nl",
  address: "Hermanstraat 49",
  postcode: "6433 DD",
  city: "Hoensbroek",
  location: "Hoensbroek, Limburg",
  phone: "+31 6 11 70 99 70",
  kvk: "61559598",
  iban: "NL86 INGB 0006 6086 34",
  facebook: "https://www.facebook.com/share/1Cku2KNPSY/",
  youtube: "https://www.youtube.com/@tonbodelier8697?sub_confirmation=1",
};

export const NAVIGATION = [
  { name: "Home", id: "home" },
  { name: "Galerij", id: "galerij" },
  { name: "Geschiedenis", id: "historie" },
  { name: "Jeugdraad", id: "council" },
  { name: "Agenda", id: "agenda" },
  { name: "Socials", id: "socials" },
  { name: "Word lid", id: "join" },
  { name: "Sponsoren", id: "sponsors" },
  { name: "Contact", id: "contact" },
];

export const HIGHLIGHTS = [
  {
    title: "Activiteiten",
    description: "Van proclamaties tot de grote optocht.",
    icon: "Calendar",
    cta: "Bekijk agenda",
  },
  {
    title: "Jeugdraad",
    description: "Maak kennis met onze Prins en de Raad van 11.",
    icon: "Users",
    cta: "Wie zijn wij?",
  },
  {
    title: "Word lid",
    description: "Bouw mee aan de toekomst van Gebrook.",
    icon: "UserPlus",
    cta: "Word lid",
  },
];

export const YOUTH_ROYALS = {
  name: "Jeugdprins Beau I",
  fullName: "Beau Sauvé",
  adjutant: "JCV Gebrook Raad van 11",
  age: "Seizoen 2026-2027",
  location: "Hoensbroek",
  title: "Jubileum Jeugdprins 2026-2027",
  description: "Beau Sauvé is onze nieuwe jubileum Jeugdprins Beau I. Hij werd op 22 november 2025 geproclameerd in een bomvol Partycentrum Amicitia.",
};

export const JUBILEE_INFO = {
  title: "1x11 Jaar JCV Gebrook",
  description: "Wij vieren ons 1x11-jarig jubileum! Doe mee aan onze speciale jubileumloterij.",
  lotteryUrl: "#lottery",
};

export const UPCOMING_EVENTS = [
  {
    date: "10 Nov",
    title: "Oad op Nuj",
    location: "Parkstad",
    type: "Opening",
    image: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&q=80&w=800",
    targetDate: "2026-11-10T14:11:00",
  },
  {
    date: "11 Nov",
    title: "BVLK",
    location: "Hoensbroek",
    type: "Evenement",
    image: "/bvlk.png",
    targetDate: "2026-11-11T14:11:00",
  },
  {
    date: "21 Nov",
    title: "Proclamatie JCV Gebrook",
    location: "Amicitia",
    type: "Ceremonie",
    image: "/input_file_4.png",
    targetDate: "2026-11-21T14:11:00",
  },
  {
    date: "03 Jan",
    title: "Receptie JCV Gebrook",
    location: "Amicitia",
    type: "Receptie",
    image: "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?auto=format&fit=crop&q=80&w=800",
    targetDate: "2027-01-03T14:11:00",
  },
  {
    date: "04 Feb",
    title: "Kowrenne",
    location: "Hoensbroek",
    type: "Traditie",
    image: "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?auto=format&fit=crop&q=80&w=800",
    targetDate: "2027-02-04T14:11:00",
  },
  {
    date: "05 Feb",
    title: "Scholenronde",
    location: "Scholen Gebrook",
    type: "Bezoek",
    image: "https://images.unsplash.com/photo-1523050335392-93851179ae09?auto=format&fit=crop&q=80&w=800",
    targetDate: "2027-02-05T14:11:00",
  },
  {
    date: "06 Feb",
    title: "Kinderoptocht Hoensbroek",
    location: "Centrum Hoensbroek",
    type: "Optocht",
    image: "/prins_auto.png",
    targetDate: "2027-02-06T14:11:00",
  },
  {
    date: "07 Feb",
    title: "Optocht Heerlen",
    location: "Heerlen",
    type: "Optocht",
    image: "/optocht_heerlen_2024.jpg",
    targetDate: "2027-02-07T14:11:00",
  },
  {
    date: "08 Feb",
    title: "Optocht Hoensbroek",
    location: "Hoensbroek",
    type: "Optocht",
    image: "/vlaggen.png",
    targetDate: "2027-02-08T14:11:00",
  },
  {
    date: "09 Feb",
    title: "Kindermiddag",
    location: "Amicitia",
    type: "Feest",
    image: "https://images.unsplash.com/photo-1502086223501-7ea6ecd79368?auto=format&fit=crop&q=80&w=800",
    targetDate: "2027-02-09T14:11:00",
  },
  {
    date: "09 Feb",
    title: "Lichtstoet Heerlen",
    location: "Heerlen",
    type: "Optocht",
    image: "/lichtstoet.png",
    targetDate: "2027-02-09T14:11:00",
  },
  {
    date: "09 Feb",
    title: "Abdicatie",
    location: "Amicitia",
    type: "Ceremonie",
    image: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&q=80&w=800",
    targetDate: "2027-02-09T14:11:00",
  },
  {
    date: "10 Feb",
    title: "Opruimen",
    location: "Hoensbroek",
    type: "Logistiek",
    image: "/opruimen.png",
    targetDate: "2027-02-10T14:11:00",
  },
  {
    date: "10 Feb",
    title: "Hiering begrave",
    location: "Hoensbroek",
    type: "Traditie",
    image: "/Haring.png",
    targetDate: "2027-02-10T14:11:00",
  },
];

export const NEWS_FLASH = [
  {
    id: 1,
    title: "Beau I geproclameerd als Jeugdprins",
    date: "22 Nov 2025",
    category: "Clubnieuws",
    summary: "In een bomvol Partycentrum Amicitia is Beau Sauvé officieel geproclameerd als onze nieuwe jubileum Jeugdprins Beau I.",
    image: "/prins_beau.png",
  },
  {
    id: 3,
    title: "Morgen: Braderie Hoensbroek!",
    date: "14 Mei",
    category: "Evenement",
    summary: "Niet vergeten! Morgen vindt de gezellige Braderie Hoensbroek plaats. Kom je ook even langs?",
    image: "https://images.unsplash.com/photo-1533900298318-6b8da08a523e?auto=format&fit=crop&q=80&w=800",
    url: "https://www.braderie-hoensbroek.nl/",
    targetDate: "2026-05-14T09:00:00",
  },
];

export const SPONSORS = [
  { name: "LOENIS Solution", tier: "Hoofdsponsor", url: "https://loenis-solution.nl/" },
  { name: "TB Adviesbureau", tier: "Hoofdsponsor", url: "https://www.facebook.com/p/TB-Adviesbureau-61575835046442/" },
  { name: "TRAVERDI Verkeersdiensten", tier: "Hoofdsponsor", url: "https://www.traverdi.nl/" },
  { name: "De Eetkamer", tier: "Sponsor", url: "https://www.deeetkamerhoensbroek.nl/" },
  { name: "Twan Wiermans Verhuiszorg Limburg", tier: "Sponsor", url: "https://www.verhuiszorglimburg.nl/Verhuis-Zorg-Verhuis-Bedrijf.html" },
  { name: "Solaf Grillroom-Pizzeria", tier: "Regulier", url: "http://www.solaf.nl/" },
  { name: "Friture ’t Hoentje", tier: "Regulier", url: "http://www.hoentjehoensbroek.nl/" },
  { name: "Partycentrum Amicitia", tier: "Regulier", url: "https://www.amicitiahoensbroek.nl/" },
  { name: "PLUS Danny Rosenboom", tier: "Regulier", url: "https://www.plus.nl/supermarkten/hoensbroek_plus-danny-rosenboom_799" },
  { name: "Roger Franssen", tier: "Regulier", url: "https://www.facebook.com/rofran69" },
  { name: "GM Nails", tier: "Regulier", url: "https://www.gmnails.nl/" },
  { name: "Juwelier Willems", tier: "Regulier", url: "https://nlmapnew.com/details/juwelier-willems-ChIJQ-K" },
  { name: "De Leeswinkel / Read Shop Hoensbroek", tier: "Regulier", url: "https://www.readshop.nl/winkel/hoensbroek" },
  { name: "DYF Living", tier: "Regulier", url: "https://www.facebook.com/DYFliving/" },
  { name: "BPNW Automotive", tier: "Regulier", url: "https://www.autofirst-bpnw.nl/" },
  { name: "L’Ortye Tuin Deco Bouw", tier: "Regulier", url: "http://www.lortyetuin.nl/" },
  { name: "Bloemsierkunst Huub Robeerts", tier: "Regulier", url: "http://www.bloemsierkunsthuubrobeerts.com/" },
  { name: "Offermans Fitness", tier: "Regulier", url: "https://offermansfysio.nl/fitness-oefengroepen/" },
  { name: "Bouwservice TCJ", tier: "Regulier", url: "https://bouwservicetcj.nl/" },
  { name: "Cafetaria ’t Smulhuis Hoensbroek", tier: "Regulier", url: "https://www.smulhuishoensbroek.nl/" },
  { name: "NailsandbeautybyQuille", tier: "Regulier", url: "https://www.facebook.com/profile.php?id=100063532210437" },
  { name: "Offermans Fysio", tier: "Regulier", url: "https://offermansfysio.nl/25/" },
  { name: "De Ster Mediastore", tier: "Regulier", url: "https://kledingbedrukkenhoensbroek.sowebshop.com/" },
];
